// <auto-generated />
namespace CreateBooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Autor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Autor));
        
        string IMigrationMetadata.Id
        {
            get { return "201904221206193_add_Autor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
